recipe: default.v1
language: en
pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- name: LogisticRegressionClassifier
policies:
- name: MemoizationPolicy
- name: RulePolicy
assistant_id: 20230318-180127-obliging-rook
